# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: email-client-service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='email-client-service.proto',
  package='influenzanet.email_client_service',
  syntax='proto3',
  serialized_options=b'ZFgithub.com/influenzanet/messaging-service/pkg/api/email_client_service',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x65mail-client-service.proto\x12!influenzanet.email_client_service\x1a\x1bgoogle/protobuf/empty.proto\"\xa3\x01\n\rServiceStatus\x12L\n\x06status\x18\x01 \x01(\x0e\x32<.influenzanet.email_client_service.ServiceStatus.StatusValue\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"&\n\x0bStatusValue\x12\n\n\x06NORMAL\x10\x00\x12\x0b\n\x07PROBLEM\x10\x01\"\x9d\x01\n\x0cSendEmailReq\x12\n\n\x02to\x18\x01 \x03(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12L\n\x10header_overrides\x18\x04 \x01(\x0b\x32\x32.influenzanet.email_client_service.HeaderOverrides\x12\x11\n\thigh_prio\x18\x05 \x01(\x08\"V\n\x0fHeaderOverrides\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08reply_to\x18\x03 \x03(\t\x12\x13\n\x0bno_reply_to\x18\x04 \x01(\x08\x32\xdb\x01\n\x15\x45mailClientServiceApi\x12R\n\x06Status\x12\x16.google.protobuf.Empty\x1a\x30.influenzanet.email_client_service.ServiceStatus\x12n\n\tSendEmail\x12/.influenzanet.email_client_service.SendEmailReq\x1a\x30.influenzanet.email_client_service.ServiceStatusBHZFgithub.com/influenzanet/messaging-service/pkg/api/email_client_serviceb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_SERVICESTATUS_STATUSVALUE = _descriptor.EnumDescriptor(
  name='StatusValue',
  full_name='influenzanet.email_client_service.ServiceStatus.StatusValue',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROBLEM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=220,
  serialized_end=258,
)
_sym_db.RegisterEnumDescriptor(_SERVICESTATUS_STATUSVALUE)


_SERVICESTATUS = _descriptor.Descriptor(
  name='ServiceStatus',
  full_name='influenzanet.email_client_service.ServiceStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='influenzanet.email_client_service.ServiceStatus.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='influenzanet.email_client_service.ServiceStatus.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='influenzanet.email_client_service.ServiceStatus.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVICESTATUS_STATUSVALUE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=258,
)


_SENDEMAILREQ = _descriptor.Descriptor(
  name='SendEmailReq',
  full_name='influenzanet.email_client_service.SendEmailReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='to', full_name='influenzanet.email_client_service.SendEmailReq.to', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subject', full_name='influenzanet.email_client_service.SendEmailReq.subject', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='influenzanet.email_client_service.SendEmailReq.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='header_overrides', full_name='influenzanet.email_client_service.SendEmailReq.header_overrides', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high_prio', full_name='influenzanet.email_client_service.SendEmailReq.high_prio', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=418,
)


_HEADEROVERRIDES = _descriptor.Descriptor(
  name='HeaderOverrides',
  full_name='influenzanet.email_client_service.HeaderOverrides',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='influenzanet.email_client_service.HeaderOverrides.from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender', full_name='influenzanet.email_client_service.HeaderOverrides.sender', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reply_to', full_name='influenzanet.email_client_service.HeaderOverrides.reply_to', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='no_reply_to', full_name='influenzanet.email_client_service.HeaderOverrides.no_reply_to', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=506,
)

_SERVICESTATUS.fields_by_name['status'].enum_type = _SERVICESTATUS_STATUSVALUE
_SERVICESTATUS_STATUSVALUE.containing_type = _SERVICESTATUS
_SENDEMAILREQ.fields_by_name['header_overrides'].message_type = _HEADEROVERRIDES
DESCRIPTOR.message_types_by_name['ServiceStatus'] = _SERVICESTATUS
DESCRIPTOR.message_types_by_name['SendEmailReq'] = _SENDEMAILREQ
DESCRIPTOR.message_types_by_name['HeaderOverrides'] = _HEADEROVERRIDES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceStatus = _reflection.GeneratedProtocolMessageType('ServiceStatus', (_message.Message,), {
  'DESCRIPTOR' : _SERVICESTATUS,
  '__module__' : 'email_client_service_pb2'
  # @@protoc_insertion_point(class_scope:influenzanet.email_client_service.ServiceStatus)
  })
_sym_db.RegisterMessage(ServiceStatus)

SendEmailReq = _reflection.GeneratedProtocolMessageType('SendEmailReq', (_message.Message,), {
  'DESCRIPTOR' : _SENDEMAILREQ,
  '__module__' : 'email_client_service_pb2'
  # @@protoc_insertion_point(class_scope:influenzanet.email_client_service.SendEmailReq)
  })
_sym_db.RegisterMessage(SendEmailReq)

HeaderOverrides = _reflection.GeneratedProtocolMessageType('HeaderOverrides', (_message.Message,), {
  'DESCRIPTOR' : _HEADEROVERRIDES,
  '__module__' : 'email_client_service_pb2'
  # @@protoc_insertion_point(class_scope:influenzanet.email_client_service.HeaderOverrides)
  })
_sym_db.RegisterMessage(HeaderOverrides)


DESCRIPTOR._options = None

_EMAILCLIENTSERVICEAPI = _descriptor.ServiceDescriptor(
  name='EmailClientServiceApi',
  full_name='influenzanet.email_client_service.EmailClientServiceApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=509,
  serialized_end=728,
  methods=[
  _descriptor.MethodDescriptor(
    name='Status',
    full_name='influenzanet.email_client_service.EmailClientServiceApi.Status',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SERVICESTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendEmail',
    full_name='influenzanet.email_client_service.EmailClientServiceApi.SendEmail',
    index=1,
    containing_service=None,
    input_type=_SENDEMAILREQ,
    output_type=_SERVICESTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMAILCLIENTSERVICEAPI)

DESCRIPTOR.services_by_name['EmailClientServiceApi'] = _EMAILCLIENTSERVICEAPI

# @@protoc_insertion_point(module_scope)
