# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import email_client_service_pb2 as email__client__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class EmailClientServiceApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
                '/influenzanet.email_client_service.EmailClientServiceApi/Status',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=email__client__service__pb2.ServiceStatus.FromString,
                )
        self.SendEmail = channel.unary_unary(
                '/influenzanet.email_client_service.EmailClientServiceApi/SendEmail',
                request_serializer=email__client__service__pb2.SendEmailReq.SerializeToString,
                response_deserializer=email__client__service__pb2.ServiceStatus.FromString,
                )


class EmailClientServiceApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmailClientServiceApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=email__client__service__pb2.ServiceStatus.SerializeToString,
            ),
            'SendEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEmail,
                    request_deserializer=email__client__service__pb2.SendEmailReq.FromString,
                    response_serializer=email__client__service__pb2.ServiceStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'influenzanet.email_client_service.EmailClientServiceApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmailClientServiceApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/influenzanet.email_client_service.EmailClientServiceApi/Status',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            email__client__service__pb2.ServiceStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/influenzanet.email_client_service.EmailClientServiceApi/SendEmail',
            email__client__service__pb2.SendEmailReq.SerializeToString,
            email__client__service__pb2.ServiceStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
